In [106]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report

from datetime import datetime
import itertools

In [107]:
data = pd.read_csv('test_2.csv')
# data.head()

In [108]:
# data[data['text'] == 'I want to kill myself']['bool'] = 0
# data

In [109]:
# data.info()
# data.describe()

In [110]:
negative_words = np.array(['hate', 'annoy', 'anxious', 'bad', 
                           'corrupt', 'cut', 'crazy', 'dead', 'die', 'depressed',
                          'dreadful', 'evil', 'fear', 'foul', 'frighten', 'gross',
                          'angry', 'ill', 'insane', 'injure', 'jealous', 'malicious',
                          'mean', 'monstrous', 'nobody', 'nonsense', 'pain', 'poor',
                          'quit', 'rage', 'rude', 'rotten', 'reject', 'repulsive', 'savage',
                          'scary', 'severe', 'sucks', 'ugly', 'terrible', 'upset', 'vile',
                          'wicked', 'curse', 'not', 'cannot', 'no', 'monster',
                          'trapped', 'burden', 'hopeless', 'gun', 'suicide', 'pills', 'overdose', 'never',
                          'imperfect', 'disapprove', 'hard', 'challenging', 'demanding', 'different'
                          'blame', 'painless', 'kill', 'suck', 'useless', 'strange',
                          'sucked', 'shit', 'freak', 'boring', 'sick', 'stupid', 'slow',
                          'emo', 'rip', 'awful', 'hide', 'ashamed', 'weird', 'insecure',
                          'fat', 'nothing', 'worthless', 'depression', 'bitch', 'loathe',
                          'hurt', 'hurts', 'blah', 'broken', 'worse', 'worst', 'cry', 
                          'crying', 'punch', 'died', 'moody', 'broke', 'tears', 'break',
                          'wrong', 'gone', 'forget', 'left', 'alone', 'asshole', 'ass',
                          'miss', 'dying', 'without', 'negative', 'killing', 'frown',
                          'frustrated', 'complicated', 'weak', 'bloody', 'down', 'drugs',
                          'devastated', 'disappointed', 'torture', 'violence', 'cutting'])

In [111]:
# data

## random branch of other stuff

In [112]:
from sklearn import feature_extraction

vectorizer = feature_extraction.text.CountVectorizer(
#     vocabulary=negative_words
    stop_words=['i']
    
)
X = vectorizer.fit_transform(data['text'])



In [113]:
X = X.todense()
X.shape

(27, 47)

In [114]:
y = data['bool']

In [115]:
# equivalent:
# data['bool']
# data.bool

In [116]:
X.shape

(27, 47)

In [117]:
# np.hstack((X,data['score'].reshape((27,1)).shape))

In [118]:
X_train, X_test, y_train, y_test  = train_test_split(X, y,
    train_size=0.50, 
    random_state=420)

In [119]:
model = LogisticRegression()

In [120]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [121]:
model.predict_proba(X_test)

array([[ 0.54573979,  0.45426021],
       [ 0.38923149,  0.61076851],
       [ 0.51624216,  0.48375784],
       [ 0.43697133,  0.56302867],
       [ 0.54573979,  0.45426021],
       [ 0.57714411,  0.42285589],
       [ 0.46666556,  0.53333444],
       [ 0.46666556,  0.53333444],
       [ 0.31315304,  0.68684696],
       [ 0.54573979,  0.45426021],
       [ 0.54387706,  0.45612294],
       [ 0.45445759,  0.54554241],
       [ 0.56568613,  0.43431387],
       [ 0.43697133,  0.56302867]])

In [122]:
model.coef_

array([[ 0.        ,  0.        , -0.18968058,  0.        ,  0.        ,
         0.        ,  0.31700794,  0.        ,  0.31700794, -0.36596521,
        -0.36596521, -0.61899335,  0.        , -0.44459639,  0.36614803,
         0.        ,  0.25574892, -0.18968058, -0.30949668,  0.22869687,
         0.25574892,  0.36614803,  0.        ,  0.        ,  0.        ,
        -0.30949668,  0.        ,  0.        ,  0.        ,  0.22869687,
         0.25574892,  0.22869687,  0.        ,  0.48444579,  0.        ,
         0.        ,  0.22869687, -0.44459639,  0.31700794,  0.        ,
         0.43693505,  0.31700794,  0.        ,  0.        ,  0.31700794,
         0.        ,  0.31700794]])

In [123]:
model.score(X_test,y_test)

0.8571428571428571

In [124]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,model.predict(X_test))

array([[6, 1],
       [1, 6]])

In [91]:
736/(1764+736)

0.2944

In [92]:
sum(y_test)

7

In [68]:
data_queries = pd.read_csv('test.csv')
# vectorizer_queries = feature_extraction.text.CountVectorizer(
# #     vocabulary=negative_words
    
# )
X_queries = vectorizer.transform(data_queries['text']).todense()

In [71]:
model.predict(X_queries)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

## end random branch

In [108]:
def create_vector(string, counter):
    temp = []
    splitString = string.split(" ")
    negCount = 0

    for nword in negative_words:
        temp = np.append(temp, np.array([splitString.count(nword)]))
        if splitString.count(nword) > 0:
            negCount = 1
    
    temp = np.append(temp, np.array([data.score[counter]]))
    
    return np.array(temp,negCount) 

        

In [104]:
#handling the parent interaction (input as the text string)

def unflag(string,X):
    vec = create_vector(string)
    for v,i in enumerate(X):
        if np.array_equal(v, vec[0]):
            y[i] = 0
    

In [105]:
#testing flagging
# unflag('I hate you and you a monstrous nobody')