In [2]:
%matplotlib inline

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

/Users/newuser/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
data = pd.read_csv('test_2.csv')
# data.head()

In [6]:
negative_words = np.array(['hate', 'annoy', 'anxious', 'bad', 
                           'corrupt', 'cut', 'crazy', 'dead', 'die', 'depressed',
                          'dreadful', 'evil', 'fear', 'foul', 'frighten', 'gross',
                          'angry', 'ill', 'insane', 'injure', 'jealous', 'malicious',
                          'mean', 'monstrous', 'nobody', 'nonsense', 'pain', 'poor',
                          'quit', 'rage', 'rude', 'rotten', 'reject', 'repulsive', 'savage',
                          'scary', 'severe', 'sucks', 'ugly', 'terrible', 'upset', 'vile',
                          'wicked', 'curse', 'not', 'cannot', 'no', 'monster',
                          'trapped', 'burden', 'hopeless', 'gun', 'suicide', 'pills', 'overdose', 'never',
                          'imperfect', 'disapprove', 'hard', 'challenging', 'demanding', 'different'
                          'blame', 'painless', 'kill', 'suck', 'useless', 'strange',
                          'sucked', 'shit', 'freak', 'boring', 'sick', 'stupid', 'slow',
                          'emo', 'rip', 'awful', 'hide', 'ashamed', 'weird', 'insecure',
                          'fat', 'nothing', 'worthless', 'depression', 'bitch', 'loathe',
                          'hurt', 'hurts', 'blah', 'broken', 'worse', 'worst', 'cry', 
                          'crying', 'punch', 'died', 'moody', 'broke', 'tears', 'break',
                          'wrong', 'gone', 'forget', 'left', 'alone', 'asshole', 'ass',
                          'miss', 'dying', 'without', 'negative', 'killing', 'frown',
                          'frustrated', 'complicated', 'weak', 'bloody', 'down', 'drugs',
                          'devastated', 'disappointed', 'torture', 'violence', 'cutting',
                          'punish', 'revenge'])

## random branch of other stuff

In [8]:
from sklearn import feature_extraction

vectorizer = feature_extraction.text.CountVectorizer(
#     vocabulary=negative_words
    stop_words=['i', 'am', 'is', 'feel', 'and', 'to']
    
)
X = vectorizer.fit_transform(data['text'])



In [9]:
X = X.todense()
X.shape

(100, 164)

In [10]:
y = data['bool']

In [11]:
# equivalent:
# data['bool']
# data.bool

In [12]:
X.shape

(100, 164)

In [13]:
# np.hstack((X,data['score'].reshape((27,1)).shape))

In [14]:
X_train, X_test, y_train, y_test  = train_test_split(X, y,
    train_size=0.50, 
    random_state=420)

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
model.predict_proba(X_test)

array([[ 0.52848781,  0.47151219],
       [ 0.49287287,  0.50712713],
       [ 0.52848781,  0.47151219],
       [ 0.52848781,  0.47151219],
       [ 0.55981162,  0.44018838],
       [ 0.52848781,  0.47151219],
       [ 0.48445882,  0.51554118],
       [ 0.31878317,  0.68121683],
       [ 0.59160244,  0.40839756],
       [ 0.52848781,  0.47151219],
       [ 0.52453631,  0.47546369],
       [ 0.55981162,  0.44018838],
       [ 0.4697798 ,  0.5302202 ],
       [ 0.42330224,  0.57669776],
       [ 0.56049039,  0.43950961],
       [ 0.42330224,  0.57669776],
       [ 0.52848781,  0.47151219],
       [ 0.59697273,  0.40302727],
       [ 0.52848781,  0.47151219],
       [ 0.45168372,  0.54831628],
       [ 0.79358569,  0.20641431],
       [ 0.69956104,  0.30043896],
       [ 0.63653378,  0.36346622],
       [ 0.53022053,  0.46977947],
       [ 0.52453631,  0.47546369],
       [ 0.52848781,  0.47151219],
       [ 0.60683518,  0.39316482],
       [ 0.54727621,  0.45272379],
       [ 0.46004645,

In [18]:
model.coef_

array([[-0.01269675,  0.20575673,  0.        , -0.27879242, -0.25476934,
         0.20575673,  0.36142591,  0.        , -0.27879242, -0.22622194,
         0.        ,  0.20575673, -0.31995354, -0.3254302 ,  0.        ,
        -0.37913777, -0.21750989,  0.21938797,  0.        , -0.31995354,
         0.30794483,  0.54633831,  0.        , -0.21750989,  0.        ,
         0.30794483,  0.35519041,  0.25287595, -0.25651896,  0.17625954,
         0.35519041,  0.37958311,  0.        , -0.37913777, -0.1263228 ,
         0.        ,  0.27316916,  0.27316916,  0.        ,  0.        ,
         0.        ,  0.        , -0.37913777,  0.        ,  0.24207259,
         0.35519041, -0.31995354,  0.27316916,  0.36142591,  0.        ,
         0.35519041, -0.22622194,  0.08016161, -0.37913777,  0.        ,
        -0.31995354,  0.2575546 , -0.18704654,  0.        ,  0.30794483,
         0.2998302 ,  0.        ,  0.        , -0.17938106, -0.31995354,
         0.        , -0.47464256,  0.        , -0.2

In [19]:
model.score(X_test,y_test)

0.76000000000000001

In [20]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,model.predict(X_test))

array([[27,  7],
       [ 5, 11]])

In [21]:
736/(1764+736)

0.2944

In [22]:
sum(y_test)

16

In [68]:
# data_queries = pd.read_csv('test.csv')
# vectorizer_queries = feature_extraction.text.CountVectorizer(
# #     vocabulary=negative_words
    
# )
# X_queries = vectorizer.transform(data_queries['text']).todense()

In [71]:
model.predict(X_queries)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

## end random branch

In [108]:
def create_vector(string, counter):
    temp = []
    splitString = string.split(" ")
    negCount = 0

    for nword in negative_words:
        temp = np.append(temp, np.array([splitString.count(nword)]))
        if splitString.count(nword) > 0:
            negCount = 1
    
    temp = np.append(temp, np.array([data.score[counter]]))
    
    return np.array(temp,negCount) 

        

In [104]:
#handling the parent interaction (input as the text string)

# def unflag(string,X):
#     vec = create_vector(string)
#     for v,i in enumerate(X):
#         if np.array_equal(v, vec[0]):
#             y[i] = 0
    