In [216]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report

from datetime import datetime
import itertools

In [217]:
data = pd.read_csv('test.csv')
data.head()

text  score  bool
0                 suicide  0.009     1
1   I want to kill myself  0.070     1
2          I hate my life  0.030     1
3  My life has no meaning  0.180     1
4      My friends hate me  0.040     1

In [218]:
data[data['text'] == 'I want to kill myself']['bool'] = 0
data

/Users/newuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


text  score  bool
0                             suicide  0.009     1
1               I want to kill myself  0.070     1
2                      I hate my life  0.030     1
3              My life has no meaning  0.180     1
4                  My friends hate me  0.040     1
5              I'm a burden to others  0.400     1
6                             suicide  0.009     1
7            painless suicide methods  0.160     1
8                     I feel hopeless  0.040     1
9             I wish I was never born  0.030     1
10                  I wish I was dead  0.010     1
11  I do not want to be alive anymore  0.060     1
12                     I feel trapped  0.010     1
13                          imperfect  0.940     0
14                         disapprove  0.420     0
15                       life is hard  0.410     0
16                        challenging  0.940     0
17                          demanding  0.550     0
18                           not easy  0.480     0
19                          different  0.650     0
20                     hard to fit in  0.340     0
21                               late  0.350     0
22                       i disapprove  0.390     0
23                my job is demanding  0.460     0
24                          it's hard  0.520     0
25            hackathons are not easy  0.410     0
26                       who to blame  0.580     0

In [219]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 3 columns):
text     27 non-null object
score    27 non-null float64
bool     27 non-null int64
dtypes: float64(1), int64(1), object(1)
memory usage: 728.0+ bytes


score       bool
count  27.000000  27.000000
mean    0.314370   0.481481
std     0.277855   0.509175
min     0.009000   0.000000
25%     0.040000   0.000000
50%     0.350000   0.000000
75%     0.470000   1.000000
max     0.940000   1.000000

In [220]:
negative_words = np.array(['hate', 'annoy', 'anxious', 'bad', 
                           'corrupt', 'cut', 'crazy', 'dead', 'die', 'depressed',
                          'dreadful', 'evil', 'fear', 'foul', 'frighten', 'gross',
                          'angry', 'ill', 'insane', 'injure', 'jealous', 'malicious',
                          'mean', 'monstrous', 'nobody', 'nonsense', 'pain', 'poor',
                          'quit', 'rage', 'rude', 'rotten', 'reject', 'repulsive', 'savage',
                          'scary', 'severe', 'sucks', 'ugly', 'terrible', 'upset', 'vile',
                          'wicked', 'freak', 'curse', 'not', 'cannot', 'no', 'monster',
                          'trapped', 'burden', 'hopeless', 'gun', 'suicide', 'pills', 'overdose', 'never',
                          'imperfect', 'disapprove', 'hard', 'challenging', 'demanding', 'different'
                          'blame', 'painless', 'kill'])

In [221]:
data

text  score  bool
0                             suicide  0.009     1
1               I want to kill myself  0.070     1
2                      I hate my life  0.030     1
3              My life has no meaning  0.180     1
4                  My friends hate me  0.040     1
5              I'm a burden to others  0.400     1
6                             suicide  0.009     1
7            painless suicide methods  0.160     1
8                     I feel hopeless  0.040     1
9             I wish I was never born  0.030     1
10                  I wish I was dead  0.010     1
11  I do not want to be alive anymore  0.060     1
12                     I feel trapped  0.010     1
13                          imperfect  0.940     0
14                         disapprove  0.420     0
15                       life is hard  0.410     0
16                        challenging  0.940     0
17                          demanding  0.550     0
18                           not easy  0.480     0
19                          different  0.650     0
20                     hard to fit in  0.340     0
21                               late  0.350     0
22                       i disapprove  0.390     0
23                my job is demanding  0.460     0
24                          it's hard  0.520     0
25            hackathons are not easy  0.410     0
26                       who to blame  0.580     0

## random branch of other stuff

In [222]:
from sklearn import feature_extraction

vectorizer = feature_extraction.text.CountVectorizer(vocabulary=negative_words)
X = vectorizer.fit_transform(data['text'])



In [223]:
X = X.todense()
X

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [224]:
y = data['bool']

In [225]:
# equivalent:
# data['bool']
# data.bool

In [226]:
X.shape

(27, 65)

In [227]:
np.hstack((X,data['score'].reshape((27,1)).shape))

/Users/newuser/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  if __name__ == '__main__':


ValueError: all the input arrays must have same number of dimensions

In [228]:
X_train, X_test, y_train, y_test  = train_test_split(X, y,
    train_size=0.50, 
    random_state=420)

In [229]:
model = LogisticRegression()

In [230]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [231]:
model.predict_proba(X_test)

array([[ 0.51794852,  0.48205148],
       [ 0.51794852,  0.48205148],
       [ 0.61278568,  0.38721432],
       [ 0.41503109,  0.58496891],
       [ 0.51794852,  0.48205148],
       [ 0.67361709,  0.32638291],
       [ 0.51794852,  0.48205148],
       [ 0.51794852,  0.48205148],
       [ 0.41503109,  0.58496891],
       [ 0.51794852,  0.48205148],
       [ 0.61278568,  0.38721432],
       [ 0.51794852,  0.48205148],
       [ 0.61278568,  0.38721432],
       [ 0.41503109,  0.58496891]])

In [232]:
model.coef_

array([[ 0.41503023,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.41503023,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.65276562,  0.        ,  0.41503023,  0.        ,  0.        ,
         0.41503023,  0.41503023,  0.        ,  0.41503023,  0.        ,
         0.        ,  0.        ,  0.        , -0.65276562, -0.38721196,
         0.        , -0.38721196,  0.        ,  0.        ,  0.        ]])

In [178]:
X_test[0]

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

## end random branch

In [108]:
def create_vector(string, counter):
    temp = []
    splitString = string.split(" ")
    negCount = 0

    for nword in negative_words:
        temp = np.append(temp, np.array([splitString.count(nword)]))
        if splitString.count(nword) > 0:
            negCount = 1
    
    temp = np.append(temp, np.array([data.score[counter]]))
    
    return np.array(temp,negCount) 

        

In [104]:
#handling the parent interaction (input as the text string)

def unflag(string,X):
    vec = create_vector(string)
    for v,i in enumerate(X):
        if np.array_equal(v, vec[0]):
            y[i] = 0
    

In [105]:
#testing flagging
# unflag('I hate you and you a monstrous nobody')